name: "Run Acceptance tests & Publish results"
description: "Run Acceptance tests with SerenityJS & Publish results to Netlify"

inputs:
  ENVIRONMENT_NAME:
    description: "Name of the environment where tests will run"
    required: true
  USE_CACHE:
    description: use cache for npm?
    required: false
    default: 'true'
  TESTS_SRC_DIR:
    description: "Directory where the tests src is"
    required: true
    default: './acceptance'
  TESTS_COMMAND:
    description: 'command to run tests. For example npm run test-ci'
    required: false
    default: 'npm test'
  RELEASE_CODENAME:
    description: 'Codename for release'
    required: false
    default: 'ci'
  NETLIFY_AUTH_TOKEN:
    description: "Netlify's PAT"
    required: true
  NETLIFY_SITE_ID:
    description: "API ID from your site in Netlify"
    required: true
  SLACK_WEBHOOK_QA:
    description: "Slack's webhook"
    required: true
    
#TODO: since continue-on-error is not supported on composite actions, lines using it are commented
runs:
  using: "composite"
  steps:

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: "14"

    # - name: Setting up cache
    #   uses: actions/cache@v2
    #   if: ${{ inputs.USE_CACHE }}=='true'
    #   with:
    #     path: ~/.npm
    #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    #     restore-keys: |
    #       ${{ runner.os }}-node-

    - name: Install project dependencies
      working-directory: ${{ inputs.TESTS_SRC_DIR }}
      run: npm ci
      shell: bash

    - name: print Chrome details
      run: google-chrome --version && chromedriver --version
      shell: bash
      continue-on-error: true

      #App message. See https://app.slack.com/block-kit-builder
    - name: Send pre-test Slack notification
      id: slack-pre-test
      uses: slackapi/slack-github-action@v1.19.0
      continue-on-error: true
      with:
        payload: |
          {
          "text": "Acceptance Tests",
          "icon_emoji": ":test_tube:",
          "channel": "logging-${{inputs.ENVIRONMENT_NAME}}" ,
          "blocks": [
            {
              "type": "header",
              "text": {
                "type": "plain_text",
                "text": "Acceptance tests (${{inputs.TESTS_COMMAND}}) running in this environment"
              }
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "Please do not deploy in this env until tests have finished :skull:"
              }
            },
            
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "Action run: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
              }
            }
          ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_QA }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

    - name: Run tests
      id: acceptance-tests
      working-directory: ${{ inputs.TESTS_SRC_DIR }}
      run: echo "TESTS_STATUS=success" >> $GITHUB_ENV && export NODE_ENV=${{ inputs.ENVIRONMENT_NAME }} && ${{ inputs.TESTS_COMMAND }} || echo "TESTS_STATUS=failure" >> $GITHUB_ENV
      shell: bash
      #continue-on-error: true

    - name: Deploy to Netlify
      id: publish-report
      uses: nwtgck/actions-netlify@v1.2.3
      if: always() && hashFiles('acceptance/target/site/serenity/summary.txt') != ''
      with:
        publish-dir: "./acceptance/target/site/serenity/"
        #production-branch: master #we will use deploy-preview approach
        deploy-message: Deploy Serenity reports for ${{ inputs.RELEASE_CODENAME }} release
        enable-pull-request-comment: false
        github-deployment-environment: ${{ inputs.ENVIRONMENT_NAME }}
        alias: deploy-preview-${{ inputs.RELEASE_CODENAME }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ inputs.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ inputs.NETLIFY_SITE_ID }}

    - name: Read tests summary
      id: tests-summary
      uses: andstor/file-reader-action@v1
      if: always() && hashFiles('acceptance/target/site/serenity/summary.txt') != ''
      #continue-on-error: true
      with:
        path: "acceptance/target/site/serenity/summary.txt"
        
    - name: Set slack icon
      id: setIcon
      run: |
        if [ ${{env.TESTS_STATUS}} = "success" ]; then
          echo "::set-output name=SLACK_ICON::white_check_mark"
        else
          echo "::set-output name=SLACK_ICON::warning"
        fi
      shell: bash
      if: always() 

      #App message. See https://app.slack.com/block-kit-builder
    - name: Send after-test Slack notification
      id: slack-after-test
      uses: slackapi/slack-github-action@v1.19.0
      with:
        payload: |
          {
          "text": "Test results",
          "icon_emoji": ":${{steps.setIcon.outputs.SLACK_ICON}}:",
          "channel": "logging-${{inputs.ENVIRONMENT_NAME}}" ,
          "blocks": [
            {
              "type": "header",
              "text": {
                "type": "plain_text",
                "text": "Acceptance tests for ${{inputs.RELEASE_CODENAME}} have finished!"
              }
            },
            {
              "type": "section",
              "text": {
                "type": "plain_text",
                "text": ${{ toJSON(steps.tests-summary.outputs.contents) }}
              }
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "<${{ steps.publish-report.outputs.deploy-url }}|Check out full results>"
              }
            },
            {
            "type": "divider"
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "GitHub Action build result: ${{ job.status }}"
              }
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "PR/commit: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
              }
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "Action run: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
              }
            }
          ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_QA }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      if: always() 

    - name: Fail the build if any test has failed
      if: ${{env.TESTS_STATUS != 'success'}} 
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed('Some tests failed!')

branding:
  icon: 'check-circle'
  color: 'green'