name: "Run Acceptance tests & Publish results"
description: "Run Acceptance tests with SerenityJS & Publish results to Netlify"

inputs:
  ENVIRONMENT_NAME:
    description: "Name of the environment where tests will run"
    required: true
  TESTS_SRC_DIR:
    description: "Directory where the tests src is"
    required: true
  RELEASE_CODENAME:
    description: 'Codename for release'
    required: false
    default: 'ci'
  GITHUB TOKEN:
    description: "GITHUB token for the repo with the tests"
    required: true
  NETLIFY_AUTH_TOKEN:
    description: "Netlify's PAT"
    required: true
  NETLIFY_SITE_ID:
    description: "API ID from your site in Netlify"
    required: true
  SLACK_WEBHOOK_QA:
    description: "Slack's webhook"
    required: true
    
#TODO: since if and continue-on-error are not supported on composite actions, lines using them are commented
runs:
  using: "composite"
  steps:

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
      with:
        node-version: "12"

    - name: Setting up cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install project dependencies
      working-directory: ${{ inputs.TESTS_SRC_DIR }}
      run: npm ci
      shell: bash

    - name: Run tests
      id: acceptance-tests
      working-directory: ${{ inputs.TESTS_SRC_DIR }}
      run: export NODE_ENV=${{ inputs.ENVIRONMENT_NAME }} && npm test || if [ $? -eq 0 ]; then echo "TESTS_STATUS=success" >> $GITHUB_ENV; else echo "TESTS_STATUS=failure" >> $GITHUB_ENV; fi
      shell: bash

    - name: Deploy to Netlify
      id: publish-report
      uses: nwtgck/actions-netlify@v1.2
      #if: always() && hashFiles('acceptance/target/site/serenity/summary.txt') != ''
      with:
        publish-dir: "./acceptance/target/site/serenity/"
        production-branch: master
        github-token: ${{ inputs.GITHUB_TOKEN }}
        deploy-message: Deploy Serenity reports for ${{ github.event.inputs.RELEASE_CODENAME }} release
        enable-pull-request-comment: false
        enable-commit-comment: true
        overwrites-pull-request-comment: true
        github-deployment-environment: ${{ inputs.ENVIRONMENT_NAME }}
        alias: ${{ github.event.inputs.RELEASE_CODENAME }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ inputs.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ inputs.NETLIFY_SITE_ID }}

    - name: Read tests summary
      id: tests-summary
      uses: andstor/file-reader-action@v1
      #if: always() && hashFiles('acceptance/target/site/serenity/summary.txt') != ''
      #continue-on-error: true
      with:
        path: "acceptance/target/site/serenity/summary.txt"
        
    - name: Send Slack notification (master only)
      uses: rtCamp/action-slack-notify@v2.2.0
      #if: always() && github.ref == 'refs/heads/master'
      env:
        SLACK_WEBHOOK: ${{ inputs.SLACK_WEBHOOK_QA }}
        SLACK_USERNAME: Acceptance Tests for ${{ github.event.inputs.RELEASE_CODENAME }} release
        SLACK_ICON_EMOJI: ":shipit:"
        SLACK_COLOR: ${{env.TESTS_STATUS}}  #${{job.status}}
        SLACK_CHANNEL:  logging-${{inputs.ENVIRONMENT_NAME}} 
        SLACK_TITLE: ${{ steps.tests-summary.outputs.contents }}
        SLACK_MESSAGE: ${{ steps.publish-report.outputs.deploy-url }}
        SLACK_FOOTER: ${{ format('https://github.com/{0}/commit/{1}/checks', github.repository, github.sha) }}
        MSG_MINIMAL: 'true'

branding:
  icon: 'check-circle'
  color: 'green'